[build]
  publish = "public/"

[build.environment]
  NODE_VERSION = "16"

[context.production]
  command = "yarn run build"
  environment = { TZ = "America/Los_Angeles", GATSBY_BUILD_ENV = "development" }

[context.deploy-preview]
  command = "yarn run build"
  environment = { TZ = "America/Los_Angeles", GATSBY_BUILD_ENV = "development" }

[context.branch-deploy]
  command = "yarn run build"
  environment = { TZ = "America/Los_Angeles", GATSBY_BUILD_ENV = "development" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' *; script-src 'self' 'unsafe-inline' 'unsafe-eval' www.redhat.com static.redhat.com assets.adobedtm.com dpm.demdex.net; font-src 'self' data:; img-src data: *; style-src 'self' 'unsafe-inline'"

[[headers]]
  for = "/tags/*"
  [headers.values]
    X-Robots-Tag = "noindex"
